bookLines = """
\n
   <#d993ab><bold>Discord Linking\n<reset>


        <#b58193>» <#d99ab0><u><hover:show_text:'<#ffd4e3><i>Click to copy!'><click:copy_to_clipboard:{code}>{code}</click></u> <#b58193>«
"""

linkRequest = """

<#ffd4e3>{username} requested to link this account.
<#9beba7><hover:show_text:'<#ffd4e3><i>Click to approve'>[Approve]</#9beba7> <#ffd4e3>|<#ff697b> <hover:show_text:'<#ffd4e3><i>Click to deny'>[Deny]
"""